name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  smoke-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List directory contents
      run: ls -la $(pwd)/examples/

    - name: Build app
      run: ./scripts/build.sh

    - name: Run test
      run: docker run --rm -t -v ${{ github.workspace }}/examples/:/app/solution/ oclint_checker --test studwork --format csv > report.csv
        #docker run --rm -t -v $(pwd)/examples/:/app/solution/ oclint_checker --test studwork --format csv > report.csv

    - name: Check if report.csv exists
      run: ls report.csv

    - name: Fail if report.csv does not exist
      if: failure()
      run: exit 1

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: report.csv