name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  smoke-test:

    runs-on: ubuntu:lastest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt update
        apt install -y ninja-build cmake bear g++ git python3 curl xz-utils zlib1g-dev
        ./scripts/get_oclint.sh
        ./scripts/build_rules.sh
        rm -rf /var/lib/apt/lists/*

    - name: Run test
      run: python3 scripts/entry.py --test studwork --format csv > report.csv

    - name: Check if report.csv exists
      run: ls report.csv

    - name: Fail if report.csv does not exist
      if: failure()
      run: exit 1

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: report.csv