name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  smoke-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build app
      run: docker build -t oclint_checker -f Dockerfile ./

    - name: Run test
      run: docker run --rm -t oclint_checker --test studwork --format csv > report.csv || echo "Ok"

    - name: Check if report.csv exists
      run: ls report.csv

    - name: Fail if report.csv does not exist
      if: failure()
      run: exit 1

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: report.csv
